name: 05-Display-SQ-Test-Results

on:
  workflow_dispatch:
    inputs:
      sonar_quality_gate:
        description: 'SonarQube Quality Gate Result'
        default: 'failed'
        required: true
      sonar_project_details:
        description: 'SonarQube Project Details'
        default: 'No results available'
        required: false
  repository_dispatch:
    types: [trigger-from-jenkins]

jobs:
  output-SQ-test-result:
    runs-on: ubuntu-latest
    steps:
    - name: Parse and Display SonarQube Project Details
      run: |
        echo '${{ github.event.inputs.sonar_project_details }}' | jq -r '.issues[] | {key, rule, severity, component, message, effort}'
    - name: Check SonarQube Quality Gate Result
      run: |
        if [ "${{ github.event.inputs.sonar_quality_gate }}" == "failed" ]; then
          echo "Quality Gate failed"
          exit 1
        else
          echo "Quality Gate passed"
        fi
    - name: Create HTML Report
      run: |
        formatted_details=$(echo '${{ github.event.inputs.sonar_project_details }}' | jq -r '.issues[] | {key, rule, severity, component, message, effort}' | jq -s .)
        echo "<html><body><h1>SonarQube Project Details</h1><pre>${formatted_details}</pre><h2>Quality Gate Status: ${{ github.event.inputs.sonar_quality_gate }}</h2></body></html>" > report.html
