name: 05-Display-SQ-Test-Results

on:
  workflow_dispatch:
    inputs:
      sonar_quality_gate:
        description: 'SonarQube Quality Gate Result'
        required: true
  repository_dispatch:
    types: [trigger-from-jenkins]

jobs:
  output-SQ-test-result:
    runs-on: ubuntu-latest
    steps:
      - name: Check SonarQube Quality Gate Result
        run: |
          if [ "${{ github.event.inputs.sonar_quality_gate }}" == "failed" ]; then
            echo "Quality Gate failed"
            exit 1
          else
            echo "Quality Gate passed"
          fi
